// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT_2pq_IQQPMibqcxKk1GnhxPo_yL4FP4',
    appId: '1:562194977189:web:1e55e34083269af59b584c',
    messagingSenderId: '562194977189',
    projectId: 'pg-helper',
    authDomain: 'pg-helper.firebaseapp.com',
    databaseURL: 'https://pg-helper-default-rtdb.firebaseio.com',
    storageBucket: 'pg-helper.firebasestorage.app',
    measurementId: 'G-JTRNXHJBM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEq0ZMR4uVW7_Bwx2jlhQyF7aihLvZwy8',
    appId: '1:562194977189:android:20ad5cbf593c21509b584c',
    messagingSenderId: '562194977189',
    projectId: 'pg-helper',
    databaseURL: 'https://pg-helper-default-rtdb.firebaseio.com',
    storageBucket: 'pg-helper.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmEJOw7jyW-5qmGQZfh2SZm_BAB_f6xQo',
    appId: '1:562194977189:ios:694485d6507fb7379b584c',
    messagingSenderId: '562194977189',
    projectId: 'pg-helper',
    databaseURL: 'https://pg-helper-default-rtdb.firebaseio.com',
    storageBucket: 'pg-helper.firebasestorage.app',
    iosBundleId: 'com.example.pgHelper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmEJOw7jyW-5qmGQZfh2SZm_BAB_f6xQo',
    appId: '1:562194977189:ios:694485d6507fb7379b584c',
    messagingSenderId: '562194977189',
    projectId: 'pg-helper',
    databaseURL: 'https://pg-helper-default-rtdb.firebaseio.com',
    storageBucket: 'pg-helper.firebasestorage.app',
    iosBundleId: 'com.example.pgHelper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDT_2pq_IQQPMibqcxKk1GnhxPo_yL4FP4',
    appId: '1:562194977189:web:99c749de01ed11759b584c',
    messagingSenderId: '562194977189',
    projectId: 'pg-helper',
    authDomain: 'pg-helper.firebaseapp.com',
    databaseURL: 'https://pg-helper-default-rtdb.firebaseio.com',
    storageBucket: 'pg-helper.firebasestorage.app',
    measurementId: 'G-WZGE1ZTLJW',
  );

}